language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true

script:
  - yarn lint
  # - yarn flow-typed
  # - yarn flow
  - yarn test -- --coverage
  - yarn build

before_deploy:
  - yarn build-storybook

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master

after_script:
  - yarn codecov
