[build]
  publish = "yarn build-storybook"
  command = "yarn lint && yarn test && yarn build"
[build.environment]
  NODE_VERSION = "14"
  YARN_VERSION = "1.22.10"
  DOTENV_DISPLAY_WARNING = "none"
  STORYBOOK_EXAMPLE_APP ="true"
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"